packages:
  - .

minimumReleaseAge: 10080
minimumReleaseAgeStrict: true
strictDepBuilds: true
trustPolicy: no-downgrade
blockExoticSubdeps: true

onlyBuiltDependencies:
  - esbuild
  - sharp
  - workerd

allowBuilds:
  esbuild: true
  sharp: true
  workerd: true
