name = "lazyfeed"
main = "src/index.ts"
compatibility_date = "2025-07-05"

# KV Namespace のバインド
[[kv_namespaces]]
binding = "LAZYFEED_KV"
# namespace_id は wrangler kv:namespace create で生成される
# 開発時は自動でプレビュー用namespace が使われる

# 静的アセット設定
[assets]
binding = "ASSETS"
directory = "./public"

# 監視設定
[observability]
enabled = true